---
spread_resub_work: 2
min_local_nvmeqs: 32
max_local_nvmeqs: 32

configured_nics: "ib0"

volumes_to_create:
  - name: meta-1
    size: "100G"
    raid_level: "0"
    stripe_width: "2"
    mount_point: "/beegfs/meta-1"
  - name: meta-2
    size: "100G"
    raid_level: "0"
    stripe_width: "2"
    mount_point: "/beegfs/meta-2"
  - name: storage-1
    size: "500G"
    raid_level: "0"
    stripe_width: "2"
    mount_point: "/beegfs/storage-1"
  - name: storage-2
    size: "500G"
    raid_level: "0"
    stripe_width: "2"
    mount_point: "/beegfs/storage-2"