---

- name: "Check if a volume with the same name ({{ volume_name }}) already exists"
  shell:
    cmd:
      nvmesh volume show --name {{ volume_name }}
    executable: /bin/bash
  register: check_volume
  run_once: true

- name: Create NVMesh volume ({{ volume_name }})
  shell:
    cmd:
      nvmesh volume create -n {{ volume_name }} -rl {{ volume_raid_level }} --stripe-width {{ volume_stripe_width }} -c {{ volume_size }}
    executable: /bin/bash
  when: check_volume.stdout == "[]" or
        check_volume.stdout == ""
  run_once: true

- name: Attach volumes to one host to enable partition and format
  shell:
    cmd:
      /usr/bin/nvmesh_attach_volumes {{ volume_name }}
    executable: /bin/bash
  run_once: true
