---
# TODO: a vérifier .... add_host ne s'execute que sur 1 seul nœud
- name: "Add host {{ hostvars[inventory_hostname].inventory_hostname }} to live inventory ({{ host_with_nvme_drives }})"
  add_host:
    name: "{{ hostvars[inventory_hostname].inventory_hostname }}"
    ansible_host: "{{ hostvars[inventory_hostname].inventory_hostname}}"
    groups: "{{ host_with_nvme_drives }}"

- name: Copy get_drives.sh script
  copy:
    src: get_drives.sh
    dest: /usr/bin/get_drives.sh
    mode: 0755

# Generate an array with the drive serial number and the status
- name: Get drive status
  command:
    get_drives.sh
  register: nvme_drive_list
  run_once: true
  when: inventory_hostname == groups['excelero_mgrs'][0]

- debug: var=nvme_drive_list

- name: Initialize NVMe drives (if required)
  shell:
    "/usr/bin/nvmesh drive format -y --name {{ item.split(' ')[0] }}"
  loop: "{{ nvme_drive_list.stdout_lines|default([]) }}"
  run_once: true
  when: inventory_hostname == groups['excelero_mgrs'][0] and item.split(" ")[1] == "Not_Initialized"
