---
- name: Install NVMesh core and utils
  package:
    name:
      - nvmesh-core
      - nvmesh-utils

# TODO: a revoir
- name: Initialize MANAGEMENT_SERVERS in /etc/nvmesh/nvmesh.conf
  lineinfile:
    path: "/etc/nvmesh/nvmesh.conf"
    regexp: "^MANAGEMENT_SERVERS="
    line: MANAGEMENT_SERVERS='server1:4001,server2:4001,'

- name: Initialize CONFIGURED_NICS in /etc/nvmesh/nvmesh.conf
  lineinfile:
    path: "/etc/nvmesh/nvmesh.conf"
    regexp: '^CONFIGURED_NICS='
    line: CONFIGURED_NICS="{{ configured_nics }}"

- name: Disable RDDA transport
  lineinfile:
    path: "/etc/nvmesh/nvmesh.conf"
    line: 'MLX5_RDDA_ENABLED="False"'

- name: Kernel tuning recommandations
  template:
    src: etc/modprode.d/nvmesh_options.conf.j2
    dest: /etc/modprode.d/nvmesh_options.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable and start  NVMesh client and target
  systemd:
    name:
      - nvmeshclient
      - nvmeshtarget
    state: started
    enabled: yes

- debug:
    msg: "Verify the nodes all check in to management and you now see 10 clients and 10 targets with 100 NVMe drives on the Dashboard page of the
WebUI."