---

- name: Install NVMesh core and utils
  package:
    name:
      - nvmesh-core
      - nvmesh-utils

- set_fact:
    management_server_with_port: "{{ management_server_with_port}} + [ '{{ item }}'+':4000' ]"
  loop: "{{ groups.excelero_mgrs }}"

- debug: var=management_server_with_port

# TODO: a revoir : template jinja
- name: Initialize MANAGEMENT_SERVERS in /etc/nvmesh/nvmesh.conf
  lineinfile:
    path: "/etc/nvmesh/nvmesh.conf"
    regexp: "^MANAGEMENT_SERVERS="
    line: MANAGEMENT_SERVERS='{{ ",".join(management_server_with_port) }}'

# TODO: a revoir : template jinja
- name: Initialize CONFIGURED_NICS in /etc/nvmesh/nvmesh.conf
  lineinfile:
    path: "/etc/nvmesh/nvmesh.conf"
    regexp: '^CONFIGURED_NICS='
    line: CONFIGURED_NICS="{{ configured_nics }}"

# TODO: a revoir : template jinja
- name: Disable RDDA transport
  lineinfile:
    path: "/etc/nvmesh/nvmesh.conf"
    line: 'MLX5_RDDA_ENABLED="False"'

- name: Kernel tuning recommendations
  template:
    src: etc/modprobe.d/nvmesh_options.conf.j2
    dest: /etc/modprobe.d/nvmesh_options.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable and start NVMesh client and target
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - nvmeshclient
    - nvmeshtarget

- debug:
    msg: "Verify the nodes and check in to management to see 10 clients and 10 targets with 100 NVMe drives on the Dashboard page of the
WebUI."