---
- import_tasks: install-mongodb-repository.yml

- name: Install NodeJS 12 and NVMesh management
  package:
    name:
      - nodejs:12
      - nvmesh-management

# TODO: a revoir
- name: Ensure replicaset rs0 exists
  community.mongodb.mongodb_replicaset:
    login_host: localhost
    login_user: admin
    login_password: admin
    replica_set: rs0
    members:
      - mongodb1:27017
      - mongodb2:27017
      - mongodb3:27017
  when: groups.mongod.index(inventory_hostname) == 0

- name: Start NVMesh manager
  systemd:
    name: nvmeshmgr
    state: enabled
    enabled: yes

- name: Check management WebUI
  uri:
    url: "https://{{ inventory_hostname }}"
    return_content: yes
    headers:
      Accept-Language: "en"
  retries: 10
  delay: 5
  register: result
  until: ('status' in result) and (result.status == 200 or result.status == 401)
  changed_when: false
  # when: groups.mgr.index(inventory_hostname) == 0
