---

- name: Download BeeGFS repository file
  get_url:
    url: "{{ beegfs_url_repo }}"
    # dest: "/etc/yum.repos.d/{{ beegfs_repo_filename }}"
    dest: "/etc/yum.repos.d/beegfs-rhel.repo"
    mode: '0644'
    owner: root
    group: root

name: Install BeeGFS packages
package:
  name:
    - beegfs-client
    - beegfs-helperd
    - beegfs-meta
    - beegfs-storage
    - libbeegfs-ib
    - beegfs-client-devel
  state: installed

# TODO: check ansible_facts
- name: Get NVMesh device name
  command:
    "ls /dev/nvmesh"
  register: nvmesh_device

- set_fact:
    nvmesh_device_path: "/dev/nvmesh/{{ nvmesh_device.stdout }}"

- name: Create a XFS primary partition
  community.general.parted:
    device: "{{ nvmesh_device_path }}"
    number: 1
    label: "gpt"
    part_start: "256s"
    part_end: "100%"
    state: present

- name: Format partition with XFS
  community.general.filesystem:
    fstype: xfs
    dev: "{{ nvmesh_device_path }}"
    opts: "-K -d su=4k,sw=8 -l version=2,su=4k -isize=512"

# TODO: cpu pining for process
# https://community.mellanox.com/s/article/howto-configure-and-test-beegfs-with-rdma
# https://community.mellanox.com/s/article/understanding-numa-node-for-performance-benchmarks

