---
- name: Add BeeGFS RHEL 8 repository
  yum_repository:
    name: beegfs
    description: BeeGFS 7.2 (rhel8)
    file: "{{ beegfs_repo_filename }}"
    baseurl: "{{ beegfs_repo }}"
    gpgkey: "{{ beegfs_gpgkey }}"
    gpgcheck: no

- name: Install BeeGFS packages
  dnf:
    name:
      - beegfs-client
      - beegfs-helperd
      - beegfs-meta
      - beegfs-storage
      - libbeegfs-ib
      - beegfs-client-devel
