---
- name: Configure systctl for BeeGFS in {{ systctl_file }}
  sysctl:
    name: "{{ item[0] }}"
    value: "{{ item[1] }}"
    sysctl_file: "{{ systctl_file }}"
  loop:
    - ['vm.dirty_background_ratio', '5']
    - ['vm.dirty_ratio', '10']
    - ['vm.vfs_cache_pressure', '50']
    - ['vm.min_free_kbytes', '4294967']

