# ---

# - name: Get connected NVMe drive
#   shell:
#     "lspci  | grep -i nvm"
#   register: has_nvme_drive

# - name: Create NVMesh volumes
#   include: create-nvmesh-volumes.yml

# # TODO: check ansible_facts
# - name: Get NVMesh device name
#   command: "ls /dev/nvmesh"
#   register: nvmesh_device

# - set_fact:
#     nvmesh_device_path: "/dev/nvmesh/{{ nvmesh_device.stdout }}"

# - name: Create a XFS primary partition
#   community.general.parted:
#     device: "{{ nvmesh_device_path }}"
#     number: 1
#     label: "gpt"
#     part_start: "256s"
#     part_end: "100%"
#     state: present

# - name: Format partition with XFS
#   community.general.filesystem:
#     fstype: xfs
#     dev: "{{ nvmesh_device_path }}"
#     opts: "-K -d su=4k,sw=8 -l version=2,su=4k -isize=512"
# # TODO: cpu pining for process
# # https://community.mellanox.com/s/article/howto-configure-and-test-beegfs-with-rdma
# # https://community.mellanox.com/s/article/understanding-numa-node-for-performance-benchmarks



# TODO: make the list a variable
- name: Create /beegfs directory and subdirectories
  file:
    path: "{{ directory_to_create }}"
    state: directory
  loop:
    - /etc/beegfs/inst1.d
    - /etc/beegfs/inst2.d
  loop_control:
    loop_var: directory_to_create

# - name: Add mount point to /etc/fstab
#   lineinfile:
#     path: /etc/fstab
#     regexp: "^/dev/nvmesh/{{ item.0 }}"
#     line: "/dev/nvmesh/{{ item.0 }} /beegfs/{{ item.1 }} xfs rw,noatime,nodiratime,largeio,inode64,noauto 0 0"
#   with_together:
#     - "{{ beegfs_dev_volumes }}"
#     - ["meta-1", "meta-2", "storage-1", "storage-2"]

# - name: Mount BeeGFS volumes
#   ansible.posix.mount:
#     path: /beegfs/{{ item }}
#     fstype: xfs
#     state: present
#   loop:
#     - ["meta-1", "meta-2", "storage-1", "storage-2"]

- name: Copy storage configuration to /etc
  copy:
    src: /etc/beegfs/beegfs-storage.conf
    dest: "{{ configuration_directory }}"
  loop:
    - /etc/beegfs/inst1.d
    - /etc/beegfs/inst2.d
  loop_control:
    loop_var: configuration_directory
