# ---
# # https://community.mellanox.com/s/article/howto-configure-and-test-beegfs-with-rdma
# # https://community.mellanox.com/s/article/understanding-numa-node-for-performance-benchmarks

# TODO: make the list a variable
- name: Create /beegfs directory and subdirectories
  file:
    path: "{{ directory_to_create }}"
    state: directory
  loop:
    - /etc/beegfs/inst1.d
    - /etc/beegfs/inst2.d
  loop_control:
    loop_var: directory_to_create

- name: Copy meta configuration to /etc
  copy:
    src: /etc/beegfs/beegfs-meta.conf
    dest: "{{ configuration_directory }}"
    remote_src: yes
  loop:
    - /etc/beegfs/inst1.d
    - /etc/beegfs/inst2.d
  loop_control:
    loop_var: configuration_directory

- name: Copy storage configuration to /etc
  copy:
    src: /etc/beegfs/beegfs-storage.conf
    dest: "{{ configuration_directory }}"
    remote_src: yes
  loop:
    - /etc/beegfs/inst1.d
    - /etc/beegfs/inst2.d
  loop_control:
    loop_var: configuration_directory

- name: Create service interface files
  template:
    src: etc/beegfs/interfaces.j2
    dest: /etc/beegfs/interfaces-1
  vars:
    interfaces: "{{ nic_1 }}"

- name: Create service interface files
  template:
    src: etc/beegfs/interfaces.j2
    dest: /etc/beegfs/interfaces-2
  vars:
    interfaces: "{{ nic_2 }}"

- import_tasks: modify-instance-config-files.yml

- import_tasks: register-service-on-instance.yml

- import_tasks: enable-beegfs-service.yml

- import_tasks: beegfs-sysctl-config.yml
