---
- name: Get port connected to the network
  shell:
    cmd: |
      ibdev2netdev | grep Up | awk '{ print $5 }'
    executable: /bin/bash
  register: connected_interface

- name: Get NUMA zone per interface
  shell:
    cmd: |
      cat /sys/class/net/{{ item.0 }}/device/numa_node
  register: numa_nic
  loop:
    - "{{ nic_1 }}"
    - "{{ nic_2 }}"

- name: Copy /etc/beegfs/inst1.d/beegfs-meta.conf
  template:
    src: etc/beegfs/beegfs-meta.conf.j2
    dest: /etc/beegfs/inst1.d/beegfs-meta.conf
  vars:
    connInterfacesFile: "/etc/beegfs/interfaces-1"
    connMaxInternodeNum: "64"
    connMetaPortTCP: "8015"
    connMetaPortUDP: "8015"
    connRDMATypeOfService: "106"
    logStdFile: "/var/log/beegfs-meta-1.log"
    tuneTargetChooser: "randomrobin"
    storeMetaDirectory: "/beegfs/meta-1"
    tuneBindToNumaZone: "{{ numa_nic.results.0.stdout }}"

- name: Copy /etc/beegfs/inst2.d/beegfs-meta.conf
  template:
    src: etc/beegfs/beegfs-meta.conf.j2
    dest: /etc/beegfs/inst2.d/beegfs-meta.conf
  vars:
    connInterfacesFile: "/etc/beegfs/interfaces-2"
    connMaxInternodeNum: "64"
    connMetaPortTCP: "8025"
    connMetaPortUDP: "8025"
    connRDMATypeOfService: "106"
    logStdFile: "/var/log/beegfs-meta-2.log"
    tuneTargetChooser: "randomrobin"
    storeMetaDirectory: "/beegfs/meta-2"
    tuneBindToNumaZone: "{{ numa_nic.results.1.stdout }}"

- name: Copy /etc/beegfs/inst1.d/beegfs-storage.conf
  template:
    src: etc/beegfs/beegfs-storage.conf.j2
    dest: /etc/beegfs/inst1.d/beegfs-storage.conf
  vars:
    connInterfacesFile: "/etc/beegfs/interfaces-1"
    connStoragePortTCP: "8013"
    connStoragePortUDP: "8013"
    connRDMATypeOfService: "106"
    logStdFile: "/var/log/beegfs-storage-1.log"
    tuneFileReadSize: "1m"
    tuneFileWriteSize: "1m"
    storeStorageDirectory: '/beegfs/storage-1'
    tuneBindToNumaZone: "{{ numa_nic.results.0.stdout }}"

- name: Copy /etc/beegfs/inst2.d/beegfs-storage.conf
  template:
    src: etc/beegfs/beegfs-storage.conf.j2
    dest: /etc/beegfs/inst2.d/beegfs-storage.conf
  vars:
    connInterfacesFile: "/etc/beegfs/interfaces-2"
    connStoragePortTCP: "8023"
    connStoragePortUDP: "8023"
    connRDMATypeOfService: "106"
    logStdFile: "/var/log/beegfs-storage-2.log"
    tuneFileReadSize: "1m"
    tuneFileWriteSize: "1m"
    storeStorageDirectory: '/beegfs/storage-2'
    tuneBindToNumaZone: "{{ numa_nic.results.1.stdout }}"

