---
- name: Print index
  debug:
    msg: "Index is {{ groups['beegfs_nodes'].index(inventory_hostname)|int + 1 }}"

- set_fact:
    mgmt_node: "{{ beegfs_mgmt_dns }}"
    index_node: "{{ groups['beegfs_nodes'].index(inventory_hostname)|int + 1 }}"

- name: Check if directory /beegfs/meta-1 is empty (not initialized)
  find:
    path: "/beegfs/meta-1"
  register: meta_1_already_initialized

- name: Check if directory /beegfs/meta-2 is empty (not initialized)
  find:
    path: "/beegfs/meta-2"
  register: meta_2_already_initialized

- name: Check if directory /beegfs/storage-1 is empty (not initialized)
  find:
    path: "/beegfs/storage-1"
  register: storage_1_already_initialized

- name: Check if directory /beegfs/storage-2 is empty (not initialized)
  find:
    path: "/beegfs/storage-2"
  register: storage_2_already_initialized

- name: Register the service instances on each node with unique ID (meta-1)
  shell:
    cmd: |
      /opt/beegfs/sbin/beegfs-setup-meta -c /etc/beegfs/inst1.d/beegfs-meta.conf -p /beegfs/meta-1 -s {{ index_node }}10 -S meta1-{{ index_node }}a -m {{ mgmt_node }}
    executable: /bin/bash
  when: meta_1_already_initialized.files == []

- name: Register the service instances on each node with unique ID (meta-2)
  shell:
    cmd: |
      /opt/beegfs/sbin/beegfs-setup-meta -c /etc/beegfs/inst2.d/beegfs-meta.conf -p /beegfs/meta-2 -s {{ index_node }}20 -S meta2-{{ index_node }}b -m {{ mgmt_node }}
    executable: /bin/bash
  when: meta_2_already_initialized.files == []

- name: Register the service instances on each node with unique ID (storage-1)
  shell:
    cmd: |
      /opt/beegfs/sbin/beegfs-setup-storage -c /etc/beegfs/inst1.d/beegfs-storage.conf -p /beegfs/storage-1 -s {{ index_node }}1 -i {{ index_node }}11 -S stor1-{{ index_node }}a -m {{ mgmt_node }}
    executable: /bin/bash
  when: storage_1_already_initialized.files == []

- name: Register the service instances on each node with unique ID (storage-2)
  shell:
    cmd: |
      /opt/beegfs/sbin/beegfs-setup-storage -c /etc/beegfs/inst2.d/beegfs-storage.conf -p /beegfs/storage-2 -s {{ index_node }}2 -i {{ index_node }}21 -S stor2-{{ index_node }}b -m {{ mgmt_node }}
    executable: /bin/bash
  when: storage_2_already_initialized.files == []
