---

- name: Configure ARP for execlero in {{ excelero_systctl_file }}
  sysctl:
    name: "{{ item[0] }}"
    value: "{{ item[1] }}"
    sysctl_file: "{{ excelero_systctl_file }}"
  loop:
    - ['net.ipv4.conf.all.rp_filter', '2']
    - ['net.ipv4.conf.all.arp_ignore', '2']
    - ['net.ipv4.conf.all.arp_filter', '1']
    - ['net.ipv4.conf.all.arp_announce', '2']
    - ['net.ipv4.conf.default.rp_filter', '2']
    - ['net.ipv4.conf.default.arp_ignore', '2']
    - ['net.ipv4.conf.default.arp_filter', '1']
    - ['net.ipv4.conf.default.arp_announce', '2']