---
- name: Update before install kernel sources
  package:
    name: "*"
    state: latest

- name: Install specific kernel (nvmesh build)
  dnf:
    disable_gpg_check: yes
    allow_downgrade: yes
    name:
      - https://vault.centos.org/8.2.2004/BaseOS/x86_64/os/Packages/kernel-core-{{ nvmesh_required_kernel}}.rpm
      - https://vault.centos.org/8.2.2004/BaseOS/x86_64/os/Packages/kernel-modules-{{ nvmesh_required_kernel }}.rpm
      - https://vault.centos.org/8.2.2004/BaseOS/x86_64/os/Packages/kernel-{{ nvmesh_required_kernel }}.rpm
      - https://vault.centos.org/8.2.2004/BaseOS/x86_64/os/Packages/kernel-headers-{{ nvmesh_required_kernel }}.rpm

- name: Set default kernel to boot on
  command:
    grubby --set-default=/boot/vmlinuz-{{ nvmesh_required_kernel }}

- name: Reboot host (if required) and wait for restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: hostvars[inventory_hostname]['ansible_kernel'] != nvmesh_required_kernel

- name: Install required packages
  dnf:
    name:
      - rdma-core-devel
      - createrepo
      - gdb-headless
      - rpm-build
      - python2-devel
      - tcl
      - tk
      - tcsh
      - gcc-gfortran
      - gcc
      - pciutils
      - lsof
      - make
      - unzip
      - elfutils-libelf-devel
      - perl-Term-ANSIColor
      - perl-Getopt-Long
      - python36
      - jq
    state: installed

- name: Set {{ default_python }} as default python (/usr/bin/python)
  shell:
    "alternatives --set python /usr/bin/{{ default_python }} "
