---
- name: Download NVIDIA-Mellanox OFED
  get_url:
    url: "{{ nvidia_ofed_url }}"
    dest: "{{ ofed_driver_path }}"
    mode: "0440"

- name: "Decompress {{ ofed_driver_path }}"
  unarchive:
    src: "{{ ofed_driver_path }}"
    dest: /tmp
    remote_src: yes

# - name: Change mlnxofedinstall for RHEL8.3
#   lineinfile:
#     path: "/tmp/{{ ofed_driver_name }}/mlnxofedinstall"
#     line: "} elsif ($dist_rpm =~ /(redhat|centos)-release-8'\.([0-3])-/) {'"
#     replace: "} elsif ($dist_rpm =~ /(redhat|centos)-linux-release-8'\.([0-3])-/) {'"

# - name: Copy modified mlnxofedinstall for RHEL8.3
#   copy:
#     src: 'mlnxofedinstall'
#     dest: /tmp/{{ ofed_driver_name }}/mlnxofedinstall
#     mode: '+x'


- name: Install NVIDIA-Mellanox OFED driver
  shell:
    # "/tmp/{{ ofed_driver_name }}/mlnxofedinstall --without-srp --without-isert --without-iser --without-rshim --without-mlnx-rdma-rxe --add-kernel-support --force"
    "/tmp/{{ ofed_driver_name }}/mlnxofedinstall --without-srp --without-isert --without-iser --without-rshim --without-mlnx-rdma-rxe --distro {{ os_type}}{{ os_version }} --force"
  args:
    executable: /bin/bash

#TODO: use systemd
- name: Reload driver
  shell:
    "/etc/init.d/openibd restart"