---

- name: Comment default mirror repository
  replace:
    path: "/etc/yum.repos.d/{{ item }}"
    regexp: '^(mirrorlist.*)'
    replace: '#\1'
  loop:
    - CentOS-Base.repo
    - CentOS-AppStream.repo
    - CentOS-Extras.repo

- name: Add Vault Repository in /etc/yum.repos.d/CentOS-Base.repo
  lineinfile:
    path: '/etc/yum.repos.d/CentOS-Base.repo'
    insertafter: '^#baseurl'
    line: "baseurl=https://vault.centos.org/{{ centos_version}}/BaseOS/x86_64/os/"

- name: Add Vault Repository in /etc/yum.repos.d/CentOS-AppStream.repo
  lineinfile:
    path: '/etc/yum.repos.d/CentOS-AppStream.repo'
    insertafter: '^#baseurl'
    line: "baseurl=https://vault.centos.org/{{ centos_version }}/AppStream/x86_64/os/"

- name: Add Vault Repository in /etc/yum.repos.d/CentOS-Extras.repo
  lineinfile:
    path: '/etc/yum.repos.d/CentOS-Extras.repo'
    insertafter: '^#baseurl'
    line: "baseurl=https://vault.centos.org/{{ centos_version }}/extras/x86_64/os/"


