---
- name: Start tuned and enable at boot time
  systemd:
    name: tuned
    state: started
    enabled: yes

- name: Get tuned profile
  command:
    tuned-adm active
  register: tuned_active
  changed_when: no

- name: Set built-in tuned profile
  command:
    tuned-adm profile {{ tuned_active_builtin_profile }}
  when: tuned_active_builtin_profile not in tuned_active.stdout

