- name: Install tuned.
  pakage:
    name: tuned
    state: present

- name: Start tuned and enable at boottime.
  systemd:
    name: tuned
    state: started
    enabled: true

- name: Get tuned profile.
  command: /usr/sbin/tuned-adm active
  register: tuned_active
  changed_when: false
  ignore_errors: true

- name: Set built-in tuned profile.
  command: "/usr/sbin/tuned-adm profile {{ tuned_active_builtin_profile }}"